# Copyright 2021 T-Systems MMS

# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  org1_pgdata:
  org1_walletstore:

networks:
  fabric-template-network:
    external:
      name: fabric-template-network

services:

  explorerdb.org1.mynetwork.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.org1.mynetwork.com
    hostname: explorerdb.org1.mynetwork.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - org1_pgdata:/var/lib/postgresql/data
    networks:
      - fabric-template-network

  explorer.org1.mynetwork.com:
    image: hyperledger/explorer:latest
    container_name: explorer.org1.mynetwork.com
    hostname: explorer.org1.mynetwork.com
    environment:
      - DATABASE_HOST=explorerdb.org1.mynetwork.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./explorer-config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./crypto-config:/tmp/crypto
      - org1_walletstore:/opt/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.org1.mynetwork.com:
        condition: service_healthy
    networks:
      - fabric-template-network

