# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.4'

networks:
  test:
    name: fabric-template-network

services:

  ca-org.org1.example.com:
    container_name: ca-org.org1.example.com
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org.org1.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-org-ca:/etc/hyperledger/fabric-ca-server
    networks:
      - test       
      
  ca-cli.org1.example.com:
    container_name: ca-cli.org1.example.com
    image: ubuntu:18.04
    tty: true
    working_dir: /home
    command: /bin/bash
    volumes:
        - ./crypto-config/peerOrganizations:/home/peerOrganizations
        - ./crypto-config/ordererOrganizations:/home/ordererOrganizations
        - ./fabric-orderer-ca:/home/fabric-orderer-ca
        - ./fabric-org-ca:/home/fabric-org-ca
        - ./scripts:/home/scripts
        - ../bin:/home/bin
    depends_on:
      - ca-org.org1.example.com
    networks:    
      - test
   

